package llm

import (
	"bytes"
	"context"
	"fmt"
	"os"
	"os/exec"
	"strconv"
	"strings"
	"time"

	"github.com/operator/vmvapt/internal/model"
)

// CommandProvider reaches a local model by running a fixed, operator-configured
// CLI: it passes the prompt as the final command-line argument and reads the
// completion from stdout. This is how the report narrative is generated by the
// browser's WebGPU model when vaptr runs inside the herdr v86 guest — the
// guest's `vmllm PROMPT` command bridges to the in-browser model over the host
// bridge. (The prompt is passed as an argv element rather than on stdin because
// vmllm's stdin `chat` mode requires an interactive TTY, which a piped exec is
// not; argv passing needs no TTY and returns clean stdout.)
//
// Security note: the command and its arguments come only from configuration
// (never from the model or from scanned content), it is exec'd directly with an
// explicit argv (no shell), and it receives only the finished, validated
// model.Report as prompt data. The model still cannot execute anything — it just
// returns text that becomes the report's executive summary.
type CommandProvider struct {
	// Bin is the executable to run (e.g. "vmllm"). Resolved from PATH.
	Bin string
	// Args are fixed leading arguments (e.g. ["chat"] so vmllm reads stdin).
	Args []string
	// System is an optional system prompt, passed via VMLLM_SYSTEM.
	System string
	// MaxTokens caps the completion length, passed via VMLLM_MAX_TOKENS.
	MaxTokens int
	// Timeout bounds the call; the report agent falls back to the offline
	// template if it is exceeded or the command fails.
	Timeout time.Duration
}

// DefaultVMLLM returns a CommandProvider wired for herdr's `vmllm` (WebGPU model
// in the browser). bin defaults to "vmllm" when empty.
func DefaultVMLLM(bin string, maxTokens int) CommandProvider {
	if bin == "" {
		bin = "vmllm"
	}
	if maxTokens <= 0 {
		maxTokens = 320
	}
	return CommandProvider{
		Bin:       bin,
		Args:      nil, // prompt is appended as the final argv element
		System:    reportSystemPrompt,
		MaxTokens: maxTokens,
		Timeout:   90 * time.Second,
	}
}

const reportSystemPrompt = "You are a penetration-testing report writer. Write a concise executive summary (max 150 words) for a technical audience. Describe only the findings provided; never invent findings. Plain prose, no markdown headings."

// Summarize runs the command with the report prompt on stdin and returns the
// model's completion.
func (p CommandProvider) Summarize(ctx context.Context, rep model.Report) (string, error) {
	if p.Bin == "" {
		return "", fmt.Errorf("llm: no command configured")
	}
	if p.Timeout > 0 {
		var cancel context.CancelFunc
		ctx, cancel = context.WithTimeout(ctx, p.Timeout)
		defer cancel()
	}
	// Pass the prompt as the final argv element (no shell).
	argv := append(append([]string{}, p.Args...), PromptFor(rep))
	var stdout, stderr bytes.Buffer
	cmd := exec.CommandContext(ctx, p.Bin, argv...)
	// Inherit the parent's stdin: vmllm runs `stty` and reads its RPC reply from
	// the controlling TTY, so it needs a real terminal on fd 0. Go otherwise
	// connects a child's stdin to /dev/null, which makes vmllm bail immediately
	// ("stty: standard input: Not a tty"). When vaptr's own stdin is not a TTY
	// (non-interactive run), vmllm fails and the report falls back to the
	// offline template — the desired graceful behaviour.
	cmd.Stdin = os.Stdin
	cmd.Stdout = &stdout
	cmd.Stderr = &stderr
	cmd.Env = p.env()

	if err := cmd.Run(); err != nil {
		return "", fmt.Errorf("llm: %s failed: %w (stderr: %s)", p.Bin, err, strings.TrimSpace(stderr.String()))
	}
	out := strings.TrimSpace(stdout.String())
	if out == "" {
		return "", fmt.Errorf("llm: %s returned empty output", p.Bin)
	}
	return out, nil
}

// env builds the child environment, layering the optional VMLLM_* controls on
// top of the current environment.
func (p CommandProvider) env() []string {
	env := os.Environ()
	if p.System != "" {
		env = append(env, "VMLLM_SYSTEM="+p.System)
	}
	if p.MaxTokens > 0 {
		env = append(env, "VMLLM_MAX_TOKENS="+strconv.Itoa(p.MaxTokens))
	}
	return env
}
